apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: unigames-com-tls
spec:
  secretName: unigames-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: unigames.com
  dnsNames:
    - unigames.com
    - www.unigames.com